package lab10;
/** This Java source file was (initially) generated by the Gradle 'init' task.

 @author //TODO
 @date //TODO
 CS245 Lab10 Survived Kingdoms
 */
public class Lab10 {
/**
 * TODO add javadoc
 */
    public static int survivedKingdoms(int n, int[][] listOfConflicts) {
        //TODO Add implementation here and remove TODO comments after that.
    }

    public static void main(String[] args){
        System.out.println("Hello Gradle!");
    }
}